In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the dataset

business_df = pd.read_csv('..\..\yelp_dataset\medium\yelp.business.csv')
tip_df = pd.read_csv('..\..\yelp_dataset\medium\yelp.tip.csv')
checkin_df = pd.read_csv('..\..\yelp_dataset\medium\yelp.checkin.csv')

C:\Users\User\AppData\Local\Temp\ipykernel_21292\3760120243.py:3: DtypeWarning: Columns (56,57,59) have mixed types. Specify dtype option on import or set low_memory=False.
  business_df = pd.read_csv('..\..\yelp_dataset\medium\yelp.business.csv')

#### split date on checkin for each business

In [20]:
# Split the 'date' column to multiple rows based on commas and trim spaces
checkin_df = checkin_df.assign(date=checkin_df['date'].str.split(',')).explode('date')
checkin_df['date'] = checkin_df['date'].str.strip()

# Save the processed data to a new CSV file
output_file = '..\..\yelp_dataset\medium\processed_checkin.csv'
checkin_df.to_csv(output_file, index=False)

print(f"Processed data saved to {output_file}")

Processed data saved to ..\..\yelp_dataset\medium\processed_checkin.csv

In [6]:
# Load the datasets

review_df = pd.read_csv('..\..\yelp_dataset\medium\yelp.review.csv')

In [3]:
business_df.head(3)

,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,...,attributes.AcceptsInsurance,attributes.BestNights,attributes.BYOB,attributes.Corkage,attributes.BYOBCorkage,attributes.HairSpecializesIn,attributes.Open24Hours,attributes.RestaurantsCounterService,attributes.AgesAllowed,attributes.DietaryRestrictions
0,66ea4800e59c7c5b6d879305,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,66ea4800e59c7c5b6d879306,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,66ea4800e59c7c5b6d879307,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
tip_df.head(3)

,_id,user_id,business_id,text,date,compliment_count
0,66ea489ae59c7c5b6d8be1ac,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,66ea489ae59c7c5b6d8be1ad,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,66ea489ae59c7c5b6d8be1ae,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0

In [5]:
checkin_df.head(3)

,_id,business_id,date
0,66ea4866e59c7c5b6d89de50,---kPU91CF4Lq2-WlRu9Lw,"2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020..."
1,66ea4866e59c7c5b6d89de51,--0iUa4sNDFiZFrAdIWhZQ,"2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011..."
2,66ea4866e59c7c5b6d89de52,--30_8IhuyMHbSOcNWd6DQ,"2013-06-14 23:29:17, 2014-08-13 23:20:22"

In [12]:
from textblob import TextBlob
from transformers import pipeline

c:\Lambton\Term_3\BDM 3035 - Big Data Capstone Project 01\project\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
review_output_file = '..\..\yelp_dataset\medium\processed_review_sentiment.csv'

In [14]:
# Function to determine sentiment
def get_sentiment(text):
    analysis = TextBlob(text)
    # Classify as positive if sentiment polarity is above 0, otherwise negative
    return 'Positive' if analysis.sentiment.polarity > 0 else 'Negative'

In [15]:
# Initialize the sentiment analysis pipeline using a pre-trained model
sentiment_analyzer = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
c:\Lambton\Term_3\BDM 3035 - Big Data Capstone Project 01\project\env\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\User\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [16]:
# Function to get the sentiment from the model
def get_sentiment2(text):
    result = sentiment_analyzer(text)[0]
    # Classify as positive if label is 'POSITIVE', otherwise negative
    return 'Positive' if result['label'] == 'POSITIVE' else 'Negative'

In [19]:
# Apply sentiment analysis to the 'text' column
review_df['sentiment'] = review_df['text'].apply(get_sentiment)

# Save the processed data with sentiment to a new CSV file
review_df.to_csv(review_output_file, index=False)

#### create new category from business dataset

In [35]:

category_output_file = '..\..\yelp_dataset\medium\category.csv'
business_category_output_file = '..\..\yelp_dataset\medium\category_business.csv'

In [30]:

# Split the 'categories' column into individual categories, drop NaNs, trim spaces, and explode into separate rows
categories = business_df['categories'].dropna().str.split(',').explode().str.strip()

In [31]:
# Get unique categories and create a category_id
distinct_categories = categories.drop_duplicates().reset_index(drop=True).reset_index()
distinct_categories.columns = ['category_id', 'category']
distinct_categories['category_id'] += 1  # Start IDs from 1

In [32]:

# Merge back to create a mapping of business_id to category_id
business_categories = business_df[['business_id']].join(categories)
business_categories = business_categories.merge(distinct_categories, left_on='categories', right_on='category')
business_categories = business_categories[['business_id', 'category_id']]

In [33]:

# Save the distinct categories to 'category.csv'
distinct_categories.to_csv(category_output_file, index=False)

In [36]:
# Save the business to category mapping to 'business_category.csv'
business_categories.to_csv(business_category_output_file, index=False)